openapi: 3.0.3
info:
  title: 'BABEL v1'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /v1/ftth/customer:
    get:
      summary: ''
      operationId: getV1FtthCustomer
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Unauthorized.
      tags:
        - 'FTTH Controller'
      security: []
    put:
      summary: 'Update the customer connection in Radius and reboot onu in SmartOLT'
      operationId: updateTheCustomerConnectionInRadiusAndRebootOnuInSmartOLT
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'FTTH Controller'
      security: []
  /v1/test:
    get:
      summary: 'Test RouterOS'
      operationId: testRouterOS
      description: "This endpoint allows you to test the Mikrotik server connection with this API.\nIt's a really useful endpoint and a start point to know if there is any problem.\n<aside class=\"notice\">I recommend you to use first, to debug any futher inconvenience. üòÅ</aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  name: Mikrotik-Cristian
                properties:
                  name:
                    type: string
                    example: Mikrotik-Cristian
        500:
          description: 'no payload or body params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
              required:
                - ip
      security: []
  /v1/contracts:
    get:
      summary: 'Get Contracts'
      operationId: getContracts
      description: "This endpoint allows you to get contracts information from a Mikrotik server.\n<aside class=\"notice\">This will be useful to get the clients that are in an specific router. </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  ip_server: 192.168.2.184
                  clientes_activos: 1
                  clientes_details:
                    -
                      cliente_ip: 1.1.1.1
                      download: '102400 Kbps'
                      upload: '3072 Kbps'
                      estado: activo
                properties:
                  ip_server:
                    type: string
                    example: 192.168.2.184
                  clientes_activos:
                    type: integer
                    example: 1
                  clientes_details:
                    type: array
                    example:
                      -
                        cliente_ip: 1.1.1.1
                        download: '102400 Kbps'
                        upload: '3072 Kbps'
                        estado: activo
                    items:
                      type: object
                      properties:
                        cliente_ip:
                          type: string
                          example: 1.1.1.1
                        download:
                          type: string
                          example: '102400 Kbps'
                        upload:
                          type: string
                          example: '3072 Kbps'
                        estado:
                          type: string
                          example: activo
        500:
          description: 'no payload or body params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
              required:
                - ip
      security: []
    post:
      summary: 'Create Contracts'
      operationId: createContracts
      description: "This endpoint allows you to create a 'contract or contracts' in a Mikrotik server.\n<aside class=\"notice\">With this you are able to create \"contracts\" (queues with address-list). </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'BABEL : ¬°Cola/s creada/s con √©xito!'
                properties:
                  message:
                    type: string
                    example: 'BABEL : ¬°Cola/s creada/s con √©xito!'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
                    download:
                      type: string
                      description: 'Client download speed.'
                      example: '102400 Kbps'
                    upload:
                      type: string
                      description: 'Client upload speed.'
                      example: '3072 Kbps'
                    estado:
                      type: string
                      description: 'Client status account.'
                      example: activo
              required:
                - ip
                - clientes
      security: []
    put:
      summary: 'Update Contracts'
      operationId: updateContracts
      description: "This endpoint allows you to update the banwidth profile of a 'contract or contracts' or ip in a Mikrotik server.\n<aside class=\"notice\">With this you are able to update the \"contracts\" (queues with address-list). </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'BABEL : ¬°Cola/s actualizada/s con √©xito!'
                properties:
                  message:
                    type: string
                    example: 'BABEL : ¬°Cola/s actualizada/s con √©xito!'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
                    download:
                      type: string
                      description: 'Client download speed.'
                      example: '102400 Kbps'
                    upload:
                      type: string
                      description: 'Client upload speed.'
                      example: '3072 Kbps'
                    estado:
                      type: string
                      description: 'Client status account.'
                      example: activo
              required:
                - ip
                - clientes
      security: []
    delete:
      summary: 'Delete Contracts'
      operationId: deleteContracts
      description: "This endpoint allows you to delete a 'contract or contracts' in a Mikrotik server.\n<aside class=\"notice\">With this you are able to delete the \"contracts\" (queues with address-list). BE CAREFUL üëÄ . </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'BABEL : ¬°Cola/s eliminada/s con √©xito!'
                properties:
                  message:
                    type: string
                    example: 'BABEL : ¬°Cola/s eliminada/s con √©xito!'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
                    download:
                      type: string
                      description: 'Client download speed.'
                      example: '102400 Kbps'
                    upload:
                      type: string
                      description: 'Client upload speed.'
                      example: '3072 Kbps'
                    estado:
                      type: string
                      description: 'Client status account.'
                      example: activo
              required:
                - ip
                - clientes
      security: []
  /v1.1/contracts:
    post:
      summary: 'Create Contracts'
      operationId: createContracts
      description: "This endpoint allows you to create a 'contract or contracts' in a Mikrotik server.\n<aside class=\"notice\">With this you are able to create \"contracts\" (queues with address-list). </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'BABEL : ¬°Cola/s creada/s con √©xito!'
                properties:
                  message:
                    type: string
                    example: 'BABEL : ¬°Cola/s creada/s con √©xito!'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
                    download:
                      type: string
                      description: 'Client download speed.'
                      example: '102400 Kbps'
                    upload:
                      type: string
                      description: 'Client upload speed.'
                      example: '3072 Kbps'
                    estado:
                      type: string
                      description: 'Client status account.'
                      example: activo
              required:
                - ip
                - clientes
      security: []
    put:
      summary: 'Update Contracts'
      operationId: updateContracts
      description: "This endpoint allows you to update the banwidth profile of a 'contract or contracts' or ip in a Mikrotik server.\n<aside class=\"notice\">With this you are able to update the \"contracts\" (queues with address-list). </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'BABEL : ¬°Cola/s actualizada/s con √©xito!'
                properties:
                  message:
                    type: string
                    example: 'BABEL : ¬°Cola/s actualizada/s con √©xito!'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
                    download:
                      type: string
                      description: 'Client download speed.'
                      example: '102400 Kbps'
                    upload:
                      type: string
                      description: 'Client upload speed.'
                      example: '3072 Kbps'
                    estado:
                      type: string
                      description: 'Client status account.'
                      example: activo
              required:
                - ip
                - clientes
      security: []
  /v1/connection/enableConnection:
    patch:
      summary: 'Enable Connections'
      operationId: enableConnections
      description: "This endpoint gets the ip/s in the address-list \"clientes_cortados\", then it puts it/them back in \"clientes_activos\" address-list\n<aside class=\"notice\">With this you are able to allow the \"contracts\" to have a valid connection to the internet </aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  message: 'BABEL: Operaci√≥n realizada con √©xito. Cliente/s habilitado/s'
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'BABEL: Operaci√≥n realizada con √©xito. Cliente/s habilitado/s'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
              required:
                - ip
                - clientes
      security: []
  /v1/connection/disableConnection:
    patch:
      summary: 'Disable Connections'
      operationId: disableConnections
      description: "This endpoint gets the ip/s in the address-list \"clientes_activos\", then it puts them in the \"clientes_cortados\" address-list\n<aside class=\"notice\">With this you are able to restrict the \"contracts\" to have a valid connection to the internet üòà</aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  message: 'BABEL: Operaci√≥n realizada con √©xito. Cliente/s deshabilitado/s'
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'BABEL: Operaci√≥n realizada con √©xito. Cliente/s deshabilitado/s'
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
              required:
                - ip
                - clientes
      security: []
  /v1/connection/revertChanges:
    patch:
      summary: ''
      operationId: patchV1ConnectionRevertChanges
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Mikrotik Controller'
      security: []
  /v1/router/getDataMikrotik:
    get:
      summary: 'Get Data Mikrotik'
      operationId: getDataMikrotik
      description: "This endpoint gets info from the router (clients connected, active clients, clipped, etc)\n<aside class=\"notice\">VERY USEFUL endpoint</aside>"
      parameters: []
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  name: Mikrotik-Cristian
                  server_ip: 192.168.2.184
                  queues:
                    total_queues: 1
                    queues_details:
                      -
                        name: 1.1.1.1
                        target: 1.1.1.1
                        download: '102400 Kbps'
                        upload: '3072 Kbps'
                  address_list:
                    total_address_list: 1
                    address_list_details:
                      -
                        client_ip: 1.1.1.1
                        address_list: clientes_activos
                    other_lists: 0
                  firewall:
                    clientes_activos: 1
                    clientes_cortados: 0
                  diferencias:
                    total_diferencias: 0
                    queues_sin_address: 0
                    addresses_sin_queue: 0
                    diferencias_detail: 0
                properties:
                  name:
                    type: string
                    example: Mikrotik-Cristian
                  server_ip:
                    type: string
                    example: 192.168.2.184
                  queues:
                    type: object
                    properties:
                      total_queues:
                        type: integer
                        example: 1
                      queues_details:
                        type: array
                        example:
                          -
                            name: 1.1.1.1
                            target: 1.1.1.1
                            download: '102400 Kbps'
                            upload: '3072 Kbps'
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              example: 1.1.1.1
                            target:
                              type: string
                              example: 1.1.1.1
                            download:
                              type: string
                              example: '102400 Kbps'
                            upload:
                              type: string
                              example: '3072 Kbps'
                  address_list:
                    type: object
                    properties:
                      total_address_list:
                        type: integer
                        example: 1
                      address_list_details:
                        type: array
                        example:
                          -
                            client_ip: 1.1.1.1
                            address_list: clientes_activos
                        items:
                          type: object
                          properties:
                            client_ip:
                              type: string
                              example: 1.1.1.1
                            address_list:
                              type: string
                              example: clientes_activos
                      other_lists:
                        type: integer
                        example: 0
                  firewall:
                    type: object
                    properties:
                      clientes_activos:
                        type: integer
                        example: 1
                      clientes_cortados:
                        type: integer
                        example: 0
                  diferencias:
                    type: object
                    properties:
                      total_diferencias:
                        type: integer
                        example: 0
                      queues_sin_address:
                        type: integer
                        example: 0
                      addresses_sin_queue:
                        type: integer
                        example: 0
                      diferencias_detail:
                        type: integer
                        example: 0
        500:
          description: 'no payload or missing params'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "BABEL: Undefined array key 'ip'"
                properties:
                  message:
                    type: string
                    example: "BABEL: Undefined array key 'ip'"
      tags:
        - 'Mikrotik Controller'
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: object
              properties:
                ip:
                  type: string
                  description: 'The server ip.'
                  example: 192.168.1.1
                clientes:
                  type: object
                  description: 'A list of objects that contains the clients params.'
                  example: []
                  properties:
                    cliente_ip:
                      type: string
                      description: 'Client IP.'
                      example: 1.1.1.1
              required:
                - ip
                - clientes
      security: []
  /v1/radius/users_data:
    get:
      summary: 'Get all users from the radius database'
      operationId: getAllUsersFromTheRadiusDatabase
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Unauthorized.
      tags:
        - 'Radius Controller'
      security: []
  /v1/radius/users:
    post:
      summary: 'Create a new user in the radius database'
      operationId: createANewUserInTheRadiusDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Radius Controller'
      security: []
    get:
      summary: 'Get a user from the radius database based on the username in the request'
      operationId: getAUserFromTheRadiusDatabaseBasedOnTheUsernameInTheRequest
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: Unauthorized.
      tags:
        - 'Radius Controller'
      security: []
    put:
      summary: 'Update user paramas in the radius database'
      operationId: updateUserParamasInTheRadiusDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Radius Controller'
      security: []
    delete:
      summary: 'Delete a user from the radius database.'
      operationId: deleteAUserFromTheRadiusDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Radius Controller'
      security: []
  /v1/smartolt/onu/status:
    get:
      summary: 'Get ONU Status'
      operationId: getONUStatus
      description: 'This endpoint allows you to get the status of an ONU.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer BEARER_TOKEN'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'ONU Status retrieved successfully.'
                  detail:
                    status: true
                    onu_status: Online
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'ONU Status retrieved successfully.'
                  detail:
                    type: object
                    properties:
                      status:
                        type: boolean
                        example: true
                      onu_status:
                        type: string
                        example: Online
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'Invalid data.'
                  detail:
                    onu_sn:
                      - 'The onu sn field is required.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'Invalid data.'
                  detail:
                    type: object
                    properties:
                      onu_sn:
                        type: array
                        example:
                          - 'The onu sn field is required.'
                        items:
                          type: string
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'ONU Status not found.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'ONU Status not found.'
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'An error occurred while retrieving ONU Status.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'An error occurred while retrieving ONU Status.'
      tags:
        - 'SmartOLT Controller'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                onu_sn:
                  type: string
                  description: 'The ONU serial number.'
                  example: HWTCA7A1236A
              required:
                - onu_sn
  /v1/smartolt/onu/reboot:
    post:
      summary: 'Reboot ONU'
      operationId: rebootONU
      description: 'This endpoint allows you to reboot an ONU by its serial number.'
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer BEARER_TOKEN'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'ONU rebooted successfully.'
                  detail:
                    status: true
                    response: 'Device reboot command sent'
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'ONU rebooted successfully.'
                  detail:
                    type: object
                    properties:
                      status:
                        type: boolean
                        example: true
                      response:
                        type: string
                        example: 'Device reboot command sent'
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'Invalid data.'
                  detail:
                    onu_sn:
                      - 'The onu sn field is required.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'Invalid data.'
                  detail:
                    type: object
                    properties:
                      onu_sn:
                        type: array
                        example:
                          - 'The onu sn field is required.'
                        items:
                          type: string
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'ONU Status not found.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'ONU Status not found.'
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: error
                  message: 'An error occurred while retrieving ONU Status.'
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: 'An error occurred while retrieving ONU Status.'
      tags:
        - 'SmartOLT Controller'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                onu_sn:
                  type: string
                  description: 'The ONU serial number.'
                  example: HWTCA7A1236A
              required:
                - onu_sn
tags:
  -
    name: 'FTTH Controller'
    description: 'API for managing FTTH connections'
  -
    name: 'Mikrotik Controller'
    description: 'API for managing Mikrotik'
  -
    name: 'Radius Controller'
    description: 'API for managing RADIUS'
  -
    name: 'SmartOLT Controller'
    description: "\nAPI for managing SmartOLT"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
